%Generates a GUI for use in Balloon Performance Analysis
%
%GUI is built for a 1920x1080 screen, if your resolution is different, this
%may require edits to the postion definition in hs.fig
%
%Tank Mass Calculator uses HeliumMassCalc for mass of helium
%The calculate button runs indepedently to calculate the mass
%
%AWOS Data is from an airport's Automated Weather Observing Station, 
%
%Local Data is measurements taken on-site with on-site equipment. The 
%pressure reading must be absolute/station pressure, not adjusted to be sea
%level pressure. 
%
%Payload Weight is given in pounds
%
%The Calculate button runs all the calculations and updates the tables
%The Plot button runs the calculations and plots the burst data
%
%Dependencies:
%HeliumMassCalc, AWOSMethod, LocalMethod
%   and by extention:
% MoistDensity, StandAtmo1976, CustomStandAtmo1976
function BalloonGUI4()
%Base Program provided by Steve Lente
%Modified By Michael Walker

    % Add the UI components
    hs = addcomponents();
    hs = setupCallbacks(hs);
    
    % Make figure visible after adding components
    hs.fig.Visible = 'on';

    function hs = addcomponents()

        % create figure
        hs.fig = figure(...
        'Units','pixels',...
        'Position',[240 135 845 640],... %position =[left bottom width height] edit this line to fit on screen
        'Visible','on',...
        'Color',get(0,'defaultfigureColor'),...
        'IntegerHandle','off',...
        'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
        'Name','BalloonGUI',...
        'NumberTitle','off',...
        'Tag','figure1',...
        'UserData',[],...
        'resize', 'on', ...
        'PaperPosition',get(0,'defaultfigurePaperPosition'),...
        'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
        'ScreenPixelsPerInchMode','manual',...
        'HandleVisibility','callback','MenuBar','none','Toolbar','figure');
    
    %% Tool Bar
        % modify toolbar buttons to remove ones we dont want
        buttons_to_remove = {'New Figure',...
            'Print Figure','Edit Plot','Rotate 3D','Insert Legend','Insert Colorbar'};
        for i = 1:length(buttons_to_remove)
            btn_handle = findall(hs.fig,'ToolTipString',buttons_to_remove{i});
            set(btn_handle,'Visible','Off')
        end
        clear btn_handle buttons_to_remove
        
        %Make Save and Load Buttons Do What they do
        hs.save = findall(hs.fig,'ToolTipString','Save Figure');
        hs.load = findall(hs.fig,'ToolTipString','Open File');
        
        % add custom menu options
        hs.BalloonMenu = uimenu(...
        'Parent',hs.fig,...%'Callback',@(hObject,eventdata)BalloonGUI_export('Title_1_Callback',hObject,eventdata,guidata(hObject)),...
        'Label','Commands',...
        'Tag','Title_1'...
         ); %Callback removed, unneeded

        hs.BalloonMenuCalcBtn = uimenu(...
            'Parent',hs.BalloonMenu,...
            'Label','Calculate');
        hs.BalloonMenuPlotBtn = uimenu(...
            'Parent',hs.BalloonMenu,...
            'Label','Plot');
        hs.BalloonMenuCloseBtn = uimenu(...
            'Parent',hs.BalloonMenu,...
            'Label','Close');
        
        hs.BalloonMenuLoads = uimenu(...
        'Parent',hs.fig,...
        'Label','Load Data',...
        'Tag','Title_2'...
         );
        hs.BalloonMenuOldLoadBtn = uimenu(...
            'Parent',hs.BalloonMenuLoads,...
            'Label','Old Load');
        hs.BalloonMenuDataLoadBtn = uimenu(...
            'Parent',hs.BalloonMenuLoads,...
            'Label','Load .mat');
        
        hs.BalloonMenuSaves = uimenu(...
        'Parent',hs.fig,...
        'Label','Save Data',...
        'Tag','Title_3'...
         );
         hs.BalloonMenuOldSaveBtn = uimenu(...
            'Parent',hs.BalloonMenuSaves,...
            'Label','Old Save');
        hs.BalloonMenuDataSaveBtn = uimenu(...
            'Parent',hs.BalloonMenuSaves,...
            'Label','Save as .mat');

        %% Plot Area
        % Initalize Axes
        hs.AltDiameter = axes(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultaxesFontUnits'),...
        'Units','pixels',...
        'CameraPosition',[0.5 0.5 9.16025403784439],...
        'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
        'CameraTarget',[0.5 0.5 0.5],...
        'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
        'CameraViewAngle',6.60861036031192,...
        'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
        'PlotBoxAspectRatio',[1 0.869458128078818 0.869458128078818],...
        'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
        'XTick',[0 0.2 0.4 0.6 0.8 1],...
        'XTickMode',get(0,'defaultaxesXTickMode'),...
        'XTickLabel',{  '0'; '0.2'; '0.4'; '0.6'; '0.8'; '1' },...
        'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
        'YTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
        'YTickMode',get(0,'defaultaxesYTickMode'),...
        'YTickLabel',{  '0'; '0.1'; '0.2'; '0.3'; '0.4'; '0.5'; '0.6'; '0.7'; '0.8'; '0.9'; '1' },...
        'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
        'Color',get(0,'defaultaxesColor'),...
        'CameraMode',get(0,'defaultaxesCameraMode'),...
        'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
        'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
        'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
        'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
        'XGridHandleMode',get(0,'defaultaxesXGridHandleMode'),...
        'YGridHandleMode',get(0,'defaultaxesYGridHandleMode'),...
        'XRulerMode',get(0,'defaultaxesXRulerMode'),...
        'XBaselineMode',get(0,'defaultaxesXBaselineMode'),...
        'YRulerMode',get(0,'defaultaxesYRulerMode'),...
        'YBaselineMode',get(0,'defaultaxesYBaselineMode'),...
        'ZRulerMode',get(0,'defaultaxesZRulerMode'),...
        'ZBaselineMode',get(0,'defaultaxesZBaselineMode'),...
        'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
        'XGrid','on',...
        'YGrid','on',...
        'Tag','AltDiameter',...
        'Position',[60 105 400 250],...
        'ActivePositionProperty','position',...
        'ActivePositionPropertyMode',get(0,'defaultaxesActivePositionPropertyMode'),...
        'LooseInset',[20.124 7.55615384615385 14.706 5.15192307692308],...
        'SortMethod','childorder',...
        'SortMethodMode',get(0,'defaultaxesSortMethodMode'),...
        'NextPlot','add'...
         );
% 'CreateFcn', {@local_CreateFcn, blanks(0), appdata}

        h3 = get(hs.AltDiameter,'title');

        set(h3,...
        'Parent',hs.AltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0.5 1.0 0.5],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','bottom',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','middle',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','Axes Title',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');
%          ,...

        h4 = get(hs.AltDiameter,'xlabel');

        set(h4,...
        'Parent',hs.AltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0.500000476837158 -0.0670443800567344 7.105427357601e-15],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','top',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','back',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');
%          ,...

        h5 = get(hs.AltDiameter,'ylabel');

        set(h5,...
        'Parent',hs.AltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[-0.0697865339090868 0.500000476837158 7.105427357601e-15],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',90,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','bottom',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','back',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');

        h6 = get(hs.AltDiameter,'zlabel');

        set(h6,...
        'Parent',hs.AltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0 0 0],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','right',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','middle',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','middle',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','off',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');

        hs.DiameterPlotTable = uitable(...
        'Parent',hs.fig,...
        'Units','pixels',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{'Plot Range'},...
        'ColumnWidth',{'auto'},...
        'RowName',{'Start'; 'Step'; 'End'},...
        'Position',[5 5 143 76],...
        'ColumnEditable',true,...
        'ColumnFormat',{  [] },...
        'Data',[10;0.1;11],...
        'Children',[],...
        'Tag','Diameter',...
        'UserData',[]...
         );
     
        appdata = [];
        appdata.lastValidTag = 'Diameter';
        appdata.PropertyMetaData = {  {  'DataPropertyDimension' 'DataPropertyConditionedDimension' 'DataPropertySource' 'BackgroundColorPropertyDimension' 'ColumnNameTyped' 'RowNameTyped' } {  [] 'DataExisting' [] {  'Diameter'  } {  'Start' 'Step' 'End' } } };
        
        hs.PlotUnitsMenu = uicontrol('Style', 'popup',...    
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','pixels',...
        'String', {'meters','feet'},...
        'Position', [275 30 65 15],...
        'Tag','PlotUnitsMenu'...
        );
    
        hs.PlotUnitsLabel = uicontrol(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','Altitude Units',...
        'Style','text',...
        'Position',[200 25 65 15],...
        'Children',[],...
        'Tag','PlotUnitsLable'...
         );
        
     %% Buttons and User Data
    
        hs.ButtonsPanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','pixels',...
        'Title',blanks(0),...
        'Position',[150 550 129 40],...
        'Tag','ButtonsPanel',...
        'Clipping','off'...
         );
     
        hs.CalcButton = uicontrol(...
        'Parent',hs.ButtonsPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','Calculate',...
        'Position',[5 5 55 25],...
        'Children',[],...
        'Tag','RunCalcs'...
         );
     
        hs.PlotButton = uicontrol(...
        'Parent',hs.ButtonsPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','Plot',...
        'Position',[65 5 55 25],...
        'Children',[],...
        'Tag','GenPlots'...
         );
         
        appdata = [];
        appdata.lastValidTag = 'WeatherData';
        appdata.PropertyMetaData = {  {  'DataPropertyDimension' 'DataPropertyConditionedDimension' 'DataPropertySource' 'BackgroundColorPropertyDimension' 'ColumnNameTyped' 'RowNameTyped' } {  [] 'DataExisting' [] {  'WeatherData' } {  'Temperature' 'DewPoint' 'Pressure' } } };
     
        hs.WeatherDataTable = uitable(...
        'Parent',hs.fig,...
        'Units','pixels',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'AWOS Data' 'Local Data' },...
        'ColumnWidth',{  'auto'  },...
        'RowName',{'Temperature'; 'DewPoint'; 'Presssure'},...
        'Position',[5 470 273 77],...
        'ColumnEditable',true,...
        'ColumnFormat',{ [] [] },...
        'Data',[21, 21; 15, 15; 29.92, 1013.25],...
        'Children',[],...
        'Tag','WeatherData',...
        'UserData',[]...
         );
          
        hs.LaunchDataTable = uitable(...
        'Parent',hs.fig,...
        'Units','pixels',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'Data' },...
        'ColumnWidth',{ 68.5 },...
        'RowName',{'Launch Altitude'; 'Balloon Temp °C'; 'Helium Mass'; 'Payload Mass'; 'Duct Tape Factor' },...
        'Position',[285 470 246 112],...
        'ColumnEditable',true,...
        'ColumnFormat',{ [] },...
        'Data',[0; 24; 2.47; 8.5; 1.0],...
        'Children',[],...
        'Tag','LaunchDataTable',...
        'UserData',[]...
         );
     
        hs.NameData = uitable(...
        'Parent',hs.fig,...
        'Units','pixel',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'CellEditCallback',{@NameDataCallback,hs},...
        'ColumnName',{ 'Designation','Date'},...
        'ColumnWidth',{75,65},...
        'RowName',{},...
        'Position',[5 550 142 40],...
        'ColumnEditable',true,...
        'ColumnFormat',{ [] [] },...
        'Data',{'NS-XX','2001-01-31'},...
        'Children',[],...
        'Tag','NameData',...
        'UserData',[]...
         );  
     
     %% Payload Table Area
        hs.PayloadTablePanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','pixels',...
        'Title','Payloads',...
        'Position',[472 5 370 370],...
        'Tag','PayloadTablePanel',...
        'Clipping','off'...
         );
     
        hs.PayloadTable = uitable(...
        'Parent',hs.PayloadTablePanel,...
        'Units','pixels',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'Name/Position','Rdy', 'Mass (kg)', 'Weight (lbs)', 'CO' },...
        'ColumnWidth',{ 150,25,65,70,25 },...
        'RowName',{},...
        'Position',[5 40 358 310],...
        'ColumnEditable',true,...
        'ColumnFormat',{ [] [] [] [] []},...
        'Data',{'Balloon',true,1.6,3.5274,1;'Helios',true,1.0206,2.2500,2;'Parachute',true,.9255,2.0404,3;'Command',true,1.5966,3.5200,4;'String',true,0.0830,.1829,5;'',false,0,0,6;'',false,0,0,7;'',false,0,0,8;'',false,0,0,9;'',false,.0,0,10;'',false,0,0,11;'',false,0,0,12;'',false,0,0,13;'',false,0,0,14;'',false,0,0,15},...
        'Children',[],...
        'Tag','PayloadTable',...
        'UserData',[]...
         );     
     
        hs.PayloadMassTotalLabelStatic = uicontrol(...
        'Parent',hs.PayloadTablePanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','total mass:',...
        'Style','text',...
        'Position',[145 10 55 15],...
        'Children',[],...
        'Tag','PayloadMassTotalLabelStatic'...
         );
     
        hs.PayloadMassTotalLabel = uicontrol(...
        'Parent',hs.PayloadTablePanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','0.0000',...
        'Style','text',...
        'Position',[200 10 35 15],...
        'Children',[],...
        'Tag','PayloadMassTotalLabel'...
         );
     
        hs.PayloadMassTotalUnitLabel = uicontrol(...
        'Parent',hs.PayloadTablePanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','kg',...
        'Style','text',...
        'Position',[235 10 14 15],...
        'Children',[],...
        'Tag','PayloadMassTotalUnitLabel'...
         );
     
        hs.PayloadTotalButton = uicontrol(...
        'Parent',hs.PayloadTablePanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','Calc Total',...
        'Position',[5 5 65 25],...
        'Children',[],...
        'Tag','PayloadTotalButton'...
         );
     
        hs.PayloadTotalUseButton = uicontrol(...
        'Parent',hs.PayloadTablePanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','Use Value',...
        'Position',[75 5 65 25],...
        'Children',[],...
        'Tag','PayloadTotalUse'...
         );
     
        hs.PayloadPositionChange = uicontrol(...
        'Parent',hs.PayloadTablePanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','Change Order',...
        'Position',[285 5 75 25],...
        'Children',[],...
        'Tag','PayloadPositionChange'...
         );
     
     %% Output Data Area
        hs.LiftTable = uitable(...
        'Parent',hs.fig,...
        'Units','pixels',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'AWOS Data'; 'Local Data' },...
        'ColumnWidth',{  'auto' 'auto' },...
        'RowName',{'Moist','Stnd'},...
        'Position',[5 385 218 58],...
        'ColumnEditable',[false false],...
        'ColumnFormat',{  [] [] },...
        'Data',[25.9432791808011 25.81763418819;25.9434446204095 26.0946963894714],...
        'Children',[],...
        'Tag','Lift',...
        'UserData',[]...
         );
     
        hs.LiftTabelLabel = uicontrol(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','Lift in pounds',...
        'Style','text',...
        'Position',[100 445 75 15],...
        'Children',[],...
        'Tag','text28'...
         );

        hs.DeltaLiftTable = uitable(...
        'Parent',hs.fig,...
        'Units','pixels',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'AWOS Data'; 'Local Data' },...
        'ColumnWidth',{  'auto' 'auto' },...
        'RowName',{'Moist','Stnd'},...
        'Position',[405 385 218 58],...
        'ColumnEditable',[false false],...
        'ColumnFormat',{  [] [] },...
        'Data',[2.11924534996703 1.99360035735588;2.11941078957542 2.27066255863736],...
        'Children',[],...
        'Tag','Delta',...
        'UserData',[]...
         );
     
        hs.DeltaLiftTableLabel = uicontrol(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','Delta Lift [lbs]',...
        'Style','text',...
        'Position',[510 445 75 15],...
        'Children',[],...
        'Tag','text29'...
         );

        hs.AscentRateTable = uitable(...
        'Parent',hs.fig,...
        'Units','pixels',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'AWOS Data'; 'Local Data' },...
        'ColumnWidth',{  'auto' 'auto' },...
        'RowName',{'Moist','Stnd'},...
        'Position',[625 385 218 58],...
        'ColumnEditable',[false false],...
        'ColumnFormat',{  [] [] },...
        'Data',[5.47986568267108 5.35341122239389;5.47925296461384 5.62483848444981],...
        'Children',[],...
        'Tag','Speed',...
        'UserData',[]...
         );
     
        hs.AscentRateTableLabel = uicontrol(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','Ascent Rate [m/s]',...
        'Style','text',...
        'Position',[700 445 90 15],...
        'Children',[],...
        'Tag','text30'...
         );
     
        hs.WeightTable = uitable(...
        'Parent',hs.fig,...
        'Units','pixels',...
        'ColumnName',{  'Payload Weight' },...
        'ColumnWidth',{  'auto' },...
        'RowName',{  'True'; 'w/factor' },...
        'Position',[225 385 177 58],...
        'ColumnEditable',false,...
        'ColumnFormat',{  [] },...
        'Data',[21.6582126365632;23.8240339002195],...
        'Children',[],...
        'Tag','Weight',...
        'UserData',[]...
         );

     %% Tank Mass Area
        hs.TankMassCalcPanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','pixels',...
        'TitlePosition','centertop',...
        'Title','Tank Mass Calculator',...
        'Position',[535 470 307 165],...
        'Tag','TankMassCalcPanel',...
        'Clipping','off'...
         );
     
        appdata = [];
        appdata.lastValidTag = 'Tanks';
        appdata.PropertyMetaData = {  {  'DataPropertyDimension' 'DataPropertyConditionedDimension' 'DataPropertySource' 'BackgroundColorPropertyDimension' 'ColumnNameTyped' 'RowNameTyped' } {  [] [] 'DataExisting' [] {  'Tank 1 Start' 'Tank 1 End' } {  'Pressure' 'Temperature' } } };
        
        hs.TankTable = uitable(...
        'Parent',hs.TankMassCalcPanel,...
        'Units','pixels',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'PSI Start'; 'PSI End' ; '°C Start' ; '°C End' ; 'use' },...
        'ColumnWidth',{50 50 50 50 25},...
        'RowName',{  'Tank1'; 'Tank2' ; 'Tank3' ; 'Tank4' },...
        'Position',[5 35 295 111],...
        'ColumnEditable',true,...
        'ColumnFormat',{[] [] [] [] []},...
        'Data',{2500, 100, 15, 5, true; 2500, 100, 15, 5, true; 2500, 100, 15, 5, true; 2500, 100, 15, 5, true},...
        'Children',[],...
        'Tag','Tanks',...
        'UserData',[]...
         );
     
        hs.TankCalcBtn = uicontrol(...
        'Parent',hs.TankMassCalcPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','Calculate',...
        'Position',[25 5 75 25],...
        'Children',[],...
        'Tag','HeliumTankCalc'...
         );
     
         hs.TankUseBtn = uicontrol(...
        'Parent',hs.TankMassCalcPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','Use Value',...
        'Position',[230 5 65 25],...
        'Children',[],...
        'Tag','HeliumTankUse'...
         );
     
        hs.TankMassValueLabel = uicontrol(...
        'Parent',hs.TankMassCalcPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','0',...
        'Style','text',...
        'Position',[165 10 50 15],...
        'Children',[],...
        'Tag','HeliumTankMass'...
         );
     
        hs.TankMassLabel = uicontrol(...
        'Parent',hs.TankMassCalcPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','pixels',...
        'String','kg',...
        'Style','text',...
        'Position',[210 10 15 15],...
        'Children',[],...
        'Tag','text27'...
         );
     
    end

%% Callback Functions
% Note: callbacks must be setup after handle structure is fully
% initalized due to the way structure arguments are passed between the 
% callback functions. Otherwise external structures will not be recognized
% when setting data to or pulling data from.  


    function hs = setupCallbacks(hs) %setting the callback funtions up
        set(hs.TankCalcBtn,'Callback',{@HeliumTankCalc_Callback,hs});
        set(hs.TankTable,'CellEditCallback',{@HeliumTankCalc_Callback,hs});
        set(hs.WeatherDataTable,'CellEditCallback',{@RunCalcs_Callback,hs});
        set(hs.LaunchDataTable,'CellEditCallback',{@RunCalcs_Callback,hs});
        set(hs.CalcButton,'Callback',{@RunCalcs_Callback,hs});
        set(hs.DiameterPlotTable,'CellEditCallback',{@GenPlots_Callback,hs});
        set(hs.PlotButton,'Callback',{@GenPlots_Callback,hs});
        set(hs.BalloonMenuCalcBtn,'Callback',{@GenPlots_Callback,hs});
        set(hs.BalloonMenuPlotBtn,'Callback',{@GenPlots_Callback,hs});
        set(hs.BalloonMenuCloseBtn,'Callback',{@closefcn,hs});
        set(hs.BalloonMenuOldSaveBtn,'Callback',{@oldsavebutton,hs});
        set(hs.BalloonMenuOldLoadBtn,'Callback',{@oldloadbutton,hs});
        set(hs.BalloonMenuDataSaveBtn,'Callback',{@datasavebutton,hs});
        set(hs.BalloonMenuDataLoadBtn,'Callback',{@dataloadbutton,hs});
        set(hs.PlotUnitsMenu,'Callback',{@GenPlots_Callback,hs});
        set(hs.TankUseBtn,'Callback',{@HeliumTankUse_Callback,hs});
        set(hs.PayloadTotalButton,'Callback',{@PayloadTotal,hs});
        set(hs.PayloadTable,'CellEditCallback',{@PayloadTable_EditCallback,hs});
        set(hs.PayloadTotalUseButton,'Callback',{@PayloadTotalUse,hs});
        set(hs.PayloadPositionChange,'Callback',{@PayloadPositionChange,hs});
    end

    function GenPlots_Callback(~,~,hs)
        
        %Creating the Diameter Range
        Range = get(hs.DiameterPlotTable,'Data');
        Diameter = Range(1):Range(2):Range(3);


        % calculate values to plot
        [AWOSBurst,LocalBurst] = RunCalcs_Callback(1,1,hs);
        PlotUnitsState = hs.PlotUnitsMenu.Value;
        
        axes(hs.AltDiameter)
        cla;
        hold on
        grid on 
        title 'Burst Diameter vs. Burst Altitude'
        xlabel 'diameter (meters)'
        
        if PlotUnitsState == 1
        ylabel 'altitude (meters)'
        plot(Diameter,AWOSBurst(:,1),'r')
        plot(Diameter,LocalBurst(:,1),'b')
        plot(Diameter,AWOSBurst(:,2),'g')
        plot(Diameter,LocalBurst(:,2),'k')
        legend('AWOS Standard','Local Standard','AWOS Custom','Local Custom','Location','Southeast')
%         ax3 = gca;
%         mLim = ax3.YLim;
%         yyaxis right
%         ax4 = gca;
%         ylabel 'feet'
%         set(ax4, 'YLim', mLim.*3.280839895);
        hold off
        
        elseif PlotUnitsState == 2
        ylabel 'altitude (feet)'
        plot(Diameter,unitconverter(AWOSBurst(:,1),'m','ft'),'r')
        plot(Diameter,unitconverter(LocalBurst(:,1),'m','ft'),'b')
        plot(Diameter,unitconverter(AWOSBurst(:,2),'m','ft'),'g')
        plot(Diameter,unitconverter(LocalBurst(:,2),'m','ft'),'k')
        legend('AWOS Standard','Local Standard','AWOS Method','Local Method','Location','Southeast')
%         ax1 = gca;
%         ftLim = ax1.YLim;
%         yyaxis right
%         ax2 = gca;
%         ylabel 'meters'
%         set(ax2, 'YLim', ftLim./3.280839895);
        hold off
        else
        disp('PLOT ERROR: How did you do that?')
        end
    end

    function [AWOSBurst,LocalBurst] = RunCalcs_Callback(~,~,hs)

        %Creating the Diameter Range
        Range = get(hs.DiameterPlotTable,'Data'); %Start Step End
        LaunchData = get(hs.LaunchDataTable,'Data'); %Launch Altitude; Balloon Temperature; Helium Mass; Payload Mass; Duct Tape Factor
        
        Diameter = Range(1):Range(2):Range(3);
        
        %Creating the Mass with the safety factor
        TotalMass = LaunchData(4) * LaunchData(5);

        %Creating the Data Vector for AWOSMethod
        Weather = get(hs.WeatherDataTable,'Data');
        AWOSData = [LaunchData(1);Weather(1,1);Weather(2,1);Weather(3,1);LaunchData(2);TotalMass];
        
        %Running AWOSMethod
        [AWOSLift, AWOSBurst, AWOSSpeed, AWOSDelta] = AWOSMethod(AWOSData,Diameter,LaunchData(3));

        %Creating the Data Vecotr for LocalMetho
        LocalData = [LaunchData(1);Weather(1,2);Weather(2,2);Weather(3,2);LaunchData(2);TotalMass];
        
        %Running LocalMethod
        [LocalLift, LocalBurst, LocalSpeed, LocalDelta] = LocalMethod(LocalData,Diameter,LaunchData(3));

        Weight = [LaunchData(4);TotalMass]*2.2046226218;%Converting to pounds for the weight to display

        %Putting the selected data into the table for display
        set(hs.LiftTable,'data',[AWOSLift, LocalLift])
        set(hs.DeltaLiftTable,'data',[AWOSDelta, LocalDelta])
        set(hs.AscentRateTable,'data',[AWOSSpeed, LocalSpeed])
        set(hs.WeightTable,'data',Weight)

    end

    function closefcn(~,~,hs)
    % callback for closing the window
        close(hs.fig);
    end

    function [HeliumTankMass] = HeliumTankCalc_Callback(~,~,hs)
    % performs helium tank calculations
        R_He = RCalc([0 1 0 0 0 0]);%R value for helium
        Tanks = get(hs.TankTable,'data');
        use = cell2mat(Tanks(:,5));
        Tanks = cell2mat(Tanks(:,1:4));
        TankMass = [0,0,0,0];
        for i=1:4
            TankMass(i) = GasMassCalc(R_He,48.99,Tanks(i,1),Tanks(i,3)) - GasMassCalc(R_He,48.99,Tanks(i,2),Tanks(i,4));
        end
        %TankMass1 = HeliumMassCalc(Tanks(1,1),Tanks(1,2),Tanks(1,3),Tanks(1,4),48.99/1000);
        %TankMass2 = HeliumMassCalc(Tanks(2,1),Tanks(2,2),Tanks(2,3),Tanks(2,4),48.99/1000);
        %TankMass3 = HeliumMassCalc(Tanks(3,1),Tanks(3,2),Tanks(3,3),Tanks(3,4),48.99/1000);
        %TankMass4 = HeliumMassCalc(Tanks(4,1),Tanks(4,2),Tanks(4,3),Tanks(4,4),48.99/1000);
        HeliumTankMass = TankMass(1)*use(1) + TankMass(2)*use(2) + TankMass(3)*use(3) + TankMass(4)*use(4);
        set(hs.TankMassValueLabel, 'String', HeliumTankMass )
    end

    function HeliumTankUse_Callback(~,~,hs)
        HeliumTankMass = HeliumTankCalc_Callback(1,1,hs);
        LD = get(hs.LaunchDataTable,'Data');
        LD(3) = HeliumTankMass;
        set(hs.LaunchDataTable,'Data',LD);
    end

    function NameDataCallback(src,~,hs)
        desig = string(src.Data);
        desig = append('BalloonGUI: ',desig(1));
        set(hs.fig,'Name',desig);
    end

    function oldsavebutton(~,~,hs)
        %function for saveing data
        current_dir = pwd;
        directory = uigetdir(pwd);
        cd(directory);
        FileName = uiputfile('default.txt','Save File Data');
        cd(current_dir);
        
        WeatherData = get(hs.WeatherDataTable, 'Data');
        PlotData = get(hs.DiameterPlotTable, 'Data');
        LaunchData = get(hs.LaunchDataTable, 'Data');
        Tanks = get(hs.TankTable,'Data');
        
        %Building the data to save
        FileData = [WeatherData(:,1); WeatherData(:,2); PlotData; LaunchData; Tanks(:,1); Tanks(:,2); Tanks(:,3); Tanks(:,4)];
       
        File = fopen(FileName,'wt');
        for n = 1:length(FileData)
           fprintf(File,'%f\n',FileData(n));
        end
        fclose(File);
    end

    function oldloadbutton(~,~,hs)
        %function for loading data
        current_dir = pwd;
        directory = uigetdir(pwd);
        cd(directory);
        FileName = uigetfile({'*.txt';'*.m';'*.*'},'File Selector');
        File = fopen(FileName,'r');
        FileData = fscanf(File,'%f\n',[1 Inf]);
        fclose(File);
        cd(current_dir);
        
        if (length(FileData) == 22)
        %Building data sets
        WeatherData = [FileData(1:3)', FileData(4:6)' ];
        PlotData = FileData(7:9)';
        LaunchData = FileData(10:14)';
        Tanks = [FileData(15:16)', FileData(17:18)'; FileData(19:20)', FileData(21:22)'];
        
        %Loading into GUI
        set(hs.WeatherDataTable,'Data', WeatherData)
        set(hs.DiameterPlotTable,'Data', PlotData)
        set(hs.LaunchDataTable,'Data', LaunchData)
        set(hs.TankTable,'Data',Tanks)
        set(hs.NameData,'Data',{FileName,'201X-XX-XX'})
        
        else
        disp('Invalid File Selected')
        end
    end

    function datasavebutton(~,~,hs)
        current_dir = pwd;
        directory = uigetdir(pwd);
        cd(directory);
        FileName = uiputfile('default.mat','Save File Data');
        WeatherData = hs.WeatherDataTable.Data;
        PlotData = hs.DiameterPlotTable.Data;
        LaunchData = hs.LaunchDataTable.Data;
        NameData = hs.NameData.Data;
        PayloadTable = hs.PayloadTable.Data;
        TankData = hs.TankTable.Data;
        %Above variables are used by the save function in the next line
        save(FileName,'FileName','WeatherData','PlotData','LaunchData','NameData','PayloadTable','TankData');
        cd(current_dir);
    end

    function dataloadbutton(~,~,hs)
        %function for loading data
        current_dir = pwd;
        directory = uigetdir(pwd);
        cd(directory);
        FileName = uigetfile({'*.mat';'*.m';'*.*'},'File Selector'); 
        load(FileName,'WeatherData','PlotData','LaunchData','NameData','PayloadTable','TankData'); 
        cd(current_dir);
        hs.WeatherDataTable.Data = WeatherData ;
        hs.DiameterPlotTable.Data = PlotData;
        hs.LaunchDataTable.Data =  LaunchData;
        hs.NameData.Data = NameData;
        hs.PayloadTable.Data = PayloadTable;
        hs.TankTable.Data = TankData;
    end
    

    function PayloadTable_EditCallback(src,event,hs)
        row = event.Indices(1);
        clm = event.Indices(2);
        if clm == 3
            lbs = unitconverter(event.NewData*9.80665,'N','lb');
            src.Data(row,4) = num2cell(lbs);
        elseif clm == 4
            kgs = unitconverter(event.NewData,'lb','N')./9.80665;
            src.Data(row,3) = num2cell(kgs);
        end
        
        rdy = cell2mat(src.Data(:,2));
        masses = cell2mat(src.Data(:,3));
        totalmass = sum(masses.*rdy);
        hs.PayloadMassTotalLabel.String = totalmass;
    end

    function totalmass = PayloadTotal(~,~,hs)
        totalmass = 0;
        LA = cell2mat(hs.PayloadTable.Data(:,2));
        MassA = cell2mat(hs.PayloadTable.Data(:,3));
        for i= 1:length(hs.PayloadTable.Data)
            if  LA(i) == true
                totalmass = MassA(i)+totalmass;
            end
        end
        hs.PayloadMassTotalLabel.String = totalmass; 
    end

    function PayloadTotalUse(~,~,hs)
        value = PayloadTotal(1,1,hs);
        A = get(hs.LaunchDataTable,'Data');
        A(4) = value;
        set(hs.LaunchDataTable,'Data',A)
    end

    function PayloadPositionChange(~,~,hs)
        t1 = cell2table(hs.PayloadTable.Data,'VariableNames',hs.PayloadTable.ColumnName);
        hs.PayloadTable.Data = table2cell(sortrows(t1,5));
    end
    
end