function BalloonGUI2()
%Created from BalloonGUI by Steve Lentine
%Error from BalloonGUI fixed by Michael Walker


    % Add the UI components
    hs = addcomponents();
    hs = setupCallbacks(hs);
    setdefaultvals(hs);
    
    % Make figure visible after adding components
    hs.fig.Visible = 'on';

    function hs = addcomponents()

        % create figure
        hs.fig = figure(...
        'Units','characters',...
        'Position',[103.8 -20.4615384615385 185 69.7692307692308],...
        'Visible','on',...
        'Color',get(0,'defaultfigureColor'),...
        'IntegerHandle','off',...
        'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
        'Name','BalloonGUI',...
        'NumberTitle','off',...
        'Tag','figure1',...
        'UserData',[],...
        'resize', 'off', ...
        'PaperPosition',get(0,'defaultfigurePaperPosition'),...
        'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
        'ScreenPixelsPerInchMode','manual',...
        'HandleVisibility','callback','MenuBar','none','Toolbar','figure');
    
        % modify toolbar buttons to remove ones we dont want
        buttons_to_remove = {'Save Figure','Open File','New Figure',...
            'Print Figure','Edit Plot','Rotate 3D','Insert Legend','Insert Colorbar'};
        for i = 1:length(buttons_to_remove)
            btn_handle = findall(hs.fig,'ToolTipString',buttons_to_remove{i});
            set(btn_handle,'Visible','Off')
        end
        clear btn_handle buttons_to_remove
        
        % add custom menu options
        hs.BalloonMenu = uimenu(...
        'Parent',hs.fig,...
        'Callback',@(hObject,eventdata)BalloonGUI_export('Title_1_Callback',hObject,eventdata,guidata(hObject)),...
        'Label','Balloon Performance Calculations',...
        'Tag','Title_1'...
         );

        hs.BalloonMenuCalcBtn = uimenu(...
            'Parent',hs.BalloonMenu,...
            'Label','Calculate');
        hs.BalloonMenuPlotBtn = uimenu(...
            'Parent',hs.BalloonMenu,...
            'Label','Plot');
        hs.BalloonMenuPlotBtn = uimenu(...
            'Parent',hs.BalloonMenu,...
            'Label','Close');
        
        % Initalize Axes
        hs.FeetAltDiameter = axes(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultaxesFontUnits'),...
        'Units','characters',...
        'CameraPosition',[0.5 0.5 9.16025403784439],...
        'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
        'CameraTarget',[0.5 0.5 0.5],...
        'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
        'CameraViewAngle',6.60861036031192,...
        'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
        'PlotBoxAspectRatio',[1 0.869458128078818 0.869458128078818],...
        'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
        'XTick',[0 0.2 0.4 0.6 0.8 1],...
        'XTickMode',get(0,'defaultaxesXTickMode'),...
        'XTickLabel',{  '0'; '0.2'; '0.4'; '0.6'; '0.8'; '1' },...
        'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
        'YTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
        'YTickMode',get(0,'defaultaxesYTickMode'),...
        'YTickLabel',{  '0'; '0.1'; '0.2'; '0.3'; '0.4'; '0.5'; '0.6'; '0.7'; '0.8'; '0.9'; '1' },...
        'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
        'Color',get(0,'defaultaxesColor'),...
        'CameraMode',get(0,'defaultaxesCameraMode'),...
        'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
        'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
        'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
        'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
        'XGridHandleMode',get(0,'defaultaxesXGridHandleMode'),...
        'YGridHandleMode',get(0,'defaultaxesYGridHandleMode'),...
        'XRulerMode',get(0,'defaultaxesXRulerMode'),...
        'XBaselineMode',get(0,'defaultaxesXBaselineMode'),...
        'YRulerMode',get(0,'defaultaxesYRulerMode'),...
        'YBaselineMode',get(0,'defaultaxesYBaselineMode'),...
        'ZRulerMode',get(0,'defaultaxesZRulerMode'),...
        'ZBaselineMode',get(0,'defaultaxesZBaselineMode'),...
        'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
        'XGrid','on',...
        'YGrid','on',...
        'Tag','FeetAltDiameter',...
        'Position',[9.8 11.7692307692308 81.2 27.1538461538462],...
        'ActivePositionProperty','position',...
        'ActivePositionPropertyMode',get(0,'defaultaxesActivePositionPropertyMode'),...
        'LooseInset',[20.124 7.55615384615385 14.706 5.15192307692308],...
        'SortMethod','childorder',...
        'SortMethodMode',get(0,'defaultaxesSortMethodMode'),...
        'NextPlot','add'...
         );
% 'CreateFcn', {@local_CreateFcn, blanks(0), appdata}

        h3 = get(hs.FeetAltDiameter,'title');

        set(h3,...
        'Parent',hs.FeetAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0.500000594284734 1.0070821529745 0.500000000000007],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','bottom',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','middle',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','Axes Title',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');
%          ,...

        h4 = get(hs.FeetAltDiameter,'xlabel');

        set(h4,...
        'Parent',hs.FeetAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0.500000476837158 -0.0670443800567344 7.105427357601e-15],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','top',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','back',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');
%          ,...

        h5 = get(hs.FeetAltDiameter,'ylabel');

        set(h5,...
        'Parent',hs.FeetAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[-0.0697865339090868 0.500000476837158 7.105427357601e-15],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',90,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','bottom',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','back',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');

        h6 = get(hs.FeetAltDiameter,'zlabel');

        set(h6,...
        'Parent',hs.FeetAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0 0 0],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','right',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','middle',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','middle',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','off',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');


        hs.MeterAltDiameter = axes(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultaxesFontUnits'),...
        'Units','characters',...
        'CameraPosition',[0.5 0.5 9.16025403784439],...
        'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
        'CameraTarget',[0.5 0.5 0.5],...
        'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
        'CameraViewAngle',6.60861036031192,...
        'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
        'PlotBoxAspectRatio',[1 0.869458128078818 0.869458128078818],...
        'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
        'XTick',[0 0.2 0.4 0.6 0.8 1],...
        'XTickMode',get(0,'defaultaxesXTickMode'),...
        'XTickLabel',{  '0'; '0.2'; '0.4'; '0.6'; '0.8'; '1' },...
        'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
        'YTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
        'YTickMode',get(0,'defaultaxesYTickMode'),...
        'YTickLabel',{  '0'; '0.1'; '0.2'; '0.3'; '0.4'; '0.5'; '0.6'; '0.7'; '0.8'; '0.9'; '1' },...
        'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
        'Color',get(0,'defaultaxesColor'),...
        'CameraMode',get(0,'defaultaxesCameraMode'),...
        'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
        'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
        'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
        'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
        'XRulerMode',get(0,'defaultaxesXRulerMode'),...
        'XBaselineMode',get(0,'defaultaxesXBaselineMode'),...
        'YRulerMode',get(0,'defaultaxesYRulerMode'),...
        'YBaselineMode',get(0,'defaultaxesYBaselineMode'),...
        'ZRulerMode',get(0,'defaultaxesZRulerMode'),...
        'ZBaselineMode',get(0,'defaultaxesZBaselineMode'),...
        'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
        'Tag','MeterAltDiameter',...
        'Position',[99.8 11.7692307692308 81.2 27.1538461538462],...
        'ActivePositionProperty','position',...
        'ActivePositionPropertyMode',get(0,'defaultaxesActivePositionPropertyMode'),...
        'LooseInset',[20.124 7.55615384615385 14.706 5.15192307692308],...
        'SortMethod','childorder',...
        'SortMethodMode',get(0,'defaultaxesSortMethodMode')...
         );

        h8 = get(hs.MeterAltDiameter,'title');

        set(h8,...
        'Parent',hs.MeterAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0.500001651312917 1.0070821529745 0.500000000000007],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','bottom',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','middle',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','Axes Title',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');
%          ,...

        h9 = get(hs.MeterAltDiameter,'xlabel');

        set(h9,...
        'Parent',hs.MeterAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0.500000476837158 -0.0670443800567344 7.105427357601e-15],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','top',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','back',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');

        hs.fig0 = get(hs.MeterAltDiameter,'ylabel');

        set(hs.fig0,...
        'Parent',hs.MeterAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[-0.0697865339090866 0.500000476837158 7.105427357601e-15],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',90,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','bottom',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','back',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');
%          ,...

        hs.fig1 = get(hs.MeterAltDiameter,'zlabel');

        set(hs.fig1,...
        'Parent',hs.MeterAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0 0 0],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','right',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','middle',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','middle',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','off',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');

        hs.AWOSDataPanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','characters',...
        'TitlePosition','centertop',...
        'Title','AWOS Data',...
        'Position',[2.4 59.9230769230769 30.2 9.07692307692307],...
        'Tag','AWOSDataPanel',...
        'Clipping','off'...
        );

        hs.AWOSTemp = uicontrol(...
        'Parent',hs.AWOSDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Temperature',...
        'Style','text',...
        'Position',[2.2 6.07692307692308 12.8 1.15384615384615],...
        'Children',[],...
        'Tag','text1'...
         );

        hs.AWOSDewPt = uicontrol(...
        'Parent',hs.AWOSDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Dew Point',...
        'Style','text',...
        'Position',[2.2 3.84615384615385 12.8 1.15384615384615],...
        'Children',[],...
        'Tag','text2'...
         );

        hs.AWOSPress = uicontrol(...
        'Parent',hs.AWOSDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Pressure',...
        'Style','text',...
        'Position',[2.2 1.61538461538462 12.8 1.15384615384615],...
        'Children',[],...
        'Tag','text3'...
         );

        hs.AWOSTempLabel = uicontrol(...
        'Parent',hs.AWOSDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','°C',...
        'Style','text',...
        'Position',[23.4 6 2.6 1.15384615384615],...
        'Children',[],...
        'Tag','text4'...
         );

        hs.AWOSDewPtLabel = uicontrol(...
        'Parent',hs.AWOSDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','°C',...
        'Style','text',...
        'Position',[23.4 3.76923076923077 2.6 1.15384615384615],...
        'Children',[],...
        'Tag','text5'...
         );

        hs.AWOSPresLabel = uicontrol(...
        'Parent',hs.AWOSDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','inHg',...
        'Style','text',...
        'Position',[23.4 1.53846153846154 4.8 1.15384615384615],...
        'Children',[],...
        'Tag','text6'...
         );

        hs.AWOSTempEntry = uicontrol(...
        'Parent',hs.AWOSDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','21',...
        'Style','edit',...
        'Position',[15.6 5.76923076923077 7.6 1.69230769230769],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','AWOSTemp');

        hs.AWOSDewPtEntry = uicontrol(...
        'Parent',hs.AWOSDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','edit',...
        'Position',[15.6 3.46153846153846 7.6 1.69230769230769],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','AWOSDewPoint');

        hs.AWOSPresEntry = uicontrol(...
        'Parent',hs.AWOSDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','edit',...
        'Position',[15.6 1.15384615384615 7.6 1.69230769230769],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','AWOSPress');

        hs.LocalDataPanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','characters',...
        'TitlePosition','centertop',...
        'Title','Local Data',...
        'Position',[36.0000000000001 59.9230769230769 31.8 9.07692307692307],...
        'Tag','LocalDataPanel',...
        'Clipping','off'...
         );

        hs.LocalDataTemp = uicontrol(...
        'Parent',hs.LocalDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Temperature',...
        'Style','text',...
        'Position',[2.2 6.07692307692308 12.8 1.15384615384615],...
        'Children',[],...
        'Tag','text13'...
        );

        hs.LocalDataDewPt = uicontrol(...
        'Parent',hs.LocalDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Dew Point',...
        'Style','text',...
        'Position',[2.2 3.84615384615385 12.8 1.15384615384615],...
        'Children',[],...
        'Tag','text14'...
        );

        hs.LocalDataPres = uicontrol(...
        'Parent',hs.LocalDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Pressure',...
        'Style','text',...
        'Position',[2.2 1.61538461538462 12.8 1.15384615384615],...
        'Children',[],...
        'Tag','text15'...
        );

        hs.LocalDataTempLabel = uicontrol(...
        'Parent',hs.LocalDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','°F',...
        'Style','text',...
        'Position',[25.2 6 2.6 1.15384615384615],...
        'Children',[],...
        'Tag','text16'...
         );

        hs.LocalDataDewPtLabel = uicontrol(...
        'Parent',hs.LocalDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','°F',...
        'Style','text',...
        'Position',[25.2 3.76923076923077 2.6 1.15384615384615],...
        'Children',[],...
        'Tag','text17'...
        );

        hs.LocalDataPresLabel = uicontrol(...
        'Parent',hs.LocalDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','mbar',...
        'Style','text',...
        'Position',[25.2 1.53846153846154 4.8 1.15384615384615],...
        'Children',[],...
        'Tag','text18'...
         );

        hs.LocalDataTempEntry = uicontrol(...
        'Parent',hs.LocalDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','edit',...
        'Position',[15.6 5.76923076923077 9.6 1.69230769230769],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','LocalTemp');

        hs.LocalDataDewPtEntry = uicontrol(...
        'Parent',hs.LocalDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','edit',...
        'Position',[15.6 3.46153846153846 9.6 1.69230769230769],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','LocalDewPoint');

        hs.LocalDataPresEntry = uicontrol(...
        'Parent',hs.LocalDataPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','edit',...
        'Position',[15.6 1.15384615384615 9.4 1.69230769230769],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','LocalPress');

        hs.HeliumMassPanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','characters',...
        'TitlePosition','centertop',...
        'Title','Mass of Helium',...
        'Position',[10 55.3076923076923 22.2 3.92307692307693],...
        'Tag','HeMassPanel',...
        'Clipping','off'...
         );

        hs.HeliumMassEntry= uicontrol(...
        'Parent',hs.HeliumMassPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','2.250',...
        'Style','edit',...
        'Position',[2.6 0.769230769230769 13.6 1.69230769230769],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','HeliumMass');

        hs.HeliumMassLabel = uicontrol(...
        'Parent',hs.HeliumMassPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','kg',...
        'Style','text',...
        'Position',[16.2 1.07692307692308 2.8 1.15384615384615],...
        'Children',[],...
        'Tag','text19'...
         );

        hs.PayloadMassPanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','characters',...
        'TitlePosition','centertop',...
        'Title','Payload Mass',...
        'Position',[34.8 55.3076923076923 22.2 3.92307692307693],...
        'Tag','PayloadMassPanel',...
        'Clipping','off'...
         );

        hs.PayloadMassEntry = uicontrol(...
        'Parent',hs.PayloadMassPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','edit',...
        'Position',[2.6 0.769230769230769 13.6 1.69230769230769],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','PayloadMass');

        hs.PayloadMassLabel = uicontrol(...
        'Parent',hs.PayloadMassPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','kg',...
        'Style','text',...
        'Position',[16.2 1.07692307692308 2.8 1.15384615384615],...
        'Children',[],...
        'Tag','text20'...
         );

        hs.DuctTapePanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','characters',...
        'Title','Duct Tape Factor',...
        'Position',[60 55.3076923076923 20.8 3.92307692307693],...
        'Tag','FactorPanel',...
        'Clipping','off'...
         );

        hs.DuctTapeEntry = uicontrol(...
        'Parent',hs.DuctTapePanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','edit',...
        'Position',[4.6 0.846153846153845 11.4 1.69230769230769],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','DuctTapeFactor');

        hs.ButtonsPanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','characters',...
        'Title',blanks(0),...
        'Position',[41.4 49.3846153846154 41.2 3.84615384615385],...
        'Tag','ButtonsPanel',...
        'Clipping','off'...
         );

        hs.CalcButton = uicontrol(...
        'Parent',hs.ButtonsPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Calculate',...
        'Position',[2.4 0.846153846153846 15.6 1.92307692307692],...
        'Children',[],...
        'Tag','RunCalcs'...
         );

        hs.PlotButton = uicontrol(...
        'Parent',hs.ButtonsPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Plot',...
        'Position',[22 0.846153846153846 15.6 1.92307692307692],...
        'Children',[],...
        'Tag','GenPlots'...
         );

        hs.DiameterPlotRangePanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','characters',...
        'TitlePosition','centertop',...
        'Title','Diameter Plot Range',...
        'Position',[6.4 49.0769230769231 31.4 5.23076923076923],...
        'Tag','DiameterPanel',...
        'Clipping','off'...
         );

        hs.DiameterPlotStartEntry = uicontrol(...
        'Parent',hs.DiameterPlotRangePanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','edit',...
        'Position',[1.4 1.61538461538462 8 1.92307692307692],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','RangeStart');

        hs.DiameterPlotStepEntry = uicontrol(...
        'Parent',hs.DiameterPlotRangePanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','edit',...
        'Position',[11.4 1.61538461538462 8 1.92307692307692],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','RangeStep');

        hs.DiameterPlotEndEntry = uicontrol(...
        'Parent',hs.DiameterPlotRangePanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','edit',...
        'Position',[21.4 1.61538461538462 8 1.92307692307692],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','RangeEnd');

        hs.DiameterPlotStartLabel = uicontrol(...
        'Parent',hs.DiameterPlotRangePanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Start',...
        'Style','text',...
        'Position',[1.4 0.461538461538462 8 1.15384615384615],...
        'Children',[],...
        'Tag','text21'...
         );

        hs.DiameterPlotStepLabel = uicontrol(...
        'Parent',hs.DiameterPlotRangePanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Step',...
        'Style','text',...
        'Position',[11.4 0.461538461538462 8 1.15384615384615],...
        'Children',[],...
        'Tag','text22'...
         );

        hs.DiameterPlotEndLabel = uicontrol(...
        'Parent',hs.DiameterPlotRangePanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','End',...
        'Style','text',...
        'Position',[21.4 0.461538461538462 8 1.15384615384615],...
        'Children',[],...
        'Tag','text23'...
         );

        hs.LiftTable = uitable(...
        'Parent',hs.fig,...
        'Units','characters',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'AWOS Data'; 'Local Data' },...
        'ColumnWidth',{  'auto' 'auto' },...
        'Position',[16.6 41.5384615384615 36.8 4.76923076923077],...
        'ColumnEditable',[false false],...
        'ColumnFormat',{  [] [] },...
        'Data',[25.9432791808011 25.81763418819;25.9434446204095 26.0946963894714],...
        'Children',[],...
        'Tag','Lift',...
        'UserData',[]...
         );
     
        hs.LiftTabelLabel = uicontrol(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Lift in pounds',...
        'Style','text',...
        'Position',[22.2 46.3076923076923 27.6 1.15384615384615],...
        'Children',[],...
        'Tag','text28'...
         );

        hs.DeltaLiftTable = uitable(...
        'Parent',hs.fig,...
        'Units','characters',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'AWOS Data'; 'Local Data' },...
        'ColumnWidth',{  'auto' 'auto' },...
        'Position',[97 41.6923076923077 37 4.61538461538461],...
        'ColumnEditable',[false false],...
        'ColumnFormat',{  [] [] },...
        'Data',[2.11924534996703 1.99360035735588;2.11941078957542 2.27066255863736],...
        'Children',[],...
        'Tag','Delta',...
        'UserData',[]...
         );
     
        hs.DeltaLiftTableLabel = uicontrol(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Delta Lift [lbs]',...
        'Style','text',...
        'Position',[102.2 46.3076923076923 27.6 1.15384615384615],...
        'Children',[],...
        'Tag','text29'...
         );

        hs.AscentRateTable = uitable(...
        'Parent',hs.fig,...
        'Units','characters',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'AWOS Data'; 'Local Data' },...
        'ColumnWidth',{  'auto' 'auto' },...
        'Position',[136 41.6923076923077 37 4.61538461538461],...
        'ColumnEditable',[false false],...
        'ColumnFormat',{  [] [] },...
        'Data',[5.47986568267108 5.35341122239389;5.47925296461384 5.62483848444981],...
        'Children',[],...
        'Tag','Speed',...
        'UserData',[]...
         );
     
        hs.AscentRateTableLabel = uicontrol(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Ascent Rate [m/s]',...
        'Style','text',...
        'Position',[139.8 46.3076923076923 27.6 1.15384615384615],...
        'Children',[],...
        'Tag','text30'...
         );
     
        hs.WeightTable = uitable(...
        'Parent',hs.fig,...
        'Units','characters',...
        'ColumnName',{  'Payload Weight' },...
        'ColumnWidth',{  'auto' },...
        'RowName',{  'True'; 'w/factor' },...
        'Position',[57.4 41.3076923076923 36.2 5],...
        'ColumnEditable',false,...
        'ColumnFormat',{  [] },...
        'Data',[21.6582126365632;23.8240339002195],...
        'Children',[],...
        'Tag','Weight',...
        'UserData',[]...
         );

        hs.TankMassCalcPanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','characters',...
        'TitlePosition','centertop',...
        'Title','Tank Mass Calculator',...
        'Position',[101.8 49 68.6 19],...
        'Tag','TankMassCalcPanel',...
        'Clipping','off'...
         );

        appdata = [];
        appdata.lastValidTag = 'Tank1';
        appdata.PropertyMetaData = {  {  'DataPropertyDimension' 'DataPropertyConditionedDimension' 'DataPropertySource' 'BackgroundColorPropertyDimension' 'ColumnNameTyped' 'RowNameTyped' } {  [] [] 'DataExisting' [] {  'Tank 1 Start' 'Tank 1 End' } {  'Pressure' 'Temperature' } } };

        hs.Tank1Table = uitable(...
        'Parent',hs.TankMassCalcPanel,...
        'Units','characters',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'Tank 1 Start'; 'Tank 1 End' },...
        'ColumnWidth',{  'auto' 'auto' },...
        'RowName',{  'Pressure'; 'Temperature' },...
        'Position',[3.8 12 55.2 4.69230769230769],...
        'ColumnEditable',[true true],...
        'ColumnFormat',{  [] [] },...
        'Data',[2500 100;70 60],...
        'Children',[],...
        'Tag','Tank1',...
        'UserData',[]...
         );

        appdata = [];
        appdata.lastValidTag = 'Tank2';
        appdata.PropertyMetaData = {  {  'DataPropertyDimension' 'DataPropertyConditionedDimension' 'DataPropertySource' 'BackgroundColorPropertyDimension' 'ColumnNameTyped' 'RowNameTyped' } {  [] [] 'T1' [] {  'Tank 2 Start' 'Tank 2 End' } {  'Pressure' 'Temperature' } } };

        hs.Tank2Table = uitable(...
        'Parent',hs.TankMassCalcPanel,...
        'Units','characters',...
        'ColumnName',{  'Tank 2 Start'; 'Tank 2 End' },...
        'ColumnWidth',{  'auto' 'auto' },...
        'RowName',{  'Pressure'; 'Temperature' },...
        'Position',[3.4 6.46153846153846 54.6 4.69230769230769],...
        'ColumnEditable',[true true],...
        'ColumnFormat',{  [] [] },...
        'Data',[2500 100;70 60],...
        'Children',[],...
        'Tag','Tank2',...
        'UserData',[]...
         );

        hs.TankCalcBtn = uicontrol(...
        'Parent',hs.TankMassCalcPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Calculate',...
        'Position',[3.6 2.30769230769231 22.4 2.23076923076923],...
        'Children',[],...
        'Tag','HeliumTankCalc'...
         );
     
        hs.TankMassValueLabel = uicontrol(...
        'Parent',hs.TankMassCalcPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','text',...
        'Position',[31.8 3 12.2 1.15384615384615],...
        'Children',[],...
        'Tag','HeliumTankMass'...
         );

        hs.TankMassLabel = uicontrol(...
        'Parent',hs.TankMassCalcPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','kg',...
        'Style','text',...
        'Position',[44 3 2.8 1.15384615384615],...
        'Children',[],...
        'Tag','text27'...
         );

        hs.LaunchAltPanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','characters',...
        'TitlePosition','centertop',...
        'Title','Launch Altitude',...
        'Position',[73.4 65.1538461538462 18.8 3.92307692307692],...
        'Tag','LaunchAltPanel',...
        'Clipping','off'...
         );

        hs.LaunchAltEntry = uicontrol(...
        'Parent',hs.LaunchAltPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','edit',...
        'Position',[2.6 0.615384615384615 10.6 1.69230769230769],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','LaunchAlt');

        hs.LaunchAltLabel = uicontrol(...
        'Parent',hs.LaunchAltPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','m',...
        'Style','text',...
        'Position',[13.2 1 2.6 1.15384615384615],...
        'Children',[],...
        'Tag','text24'...
         );

        hs.BalloonTempPanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','characters',...
        'TitlePosition','centertop',...
        'Title','Balloon Temperature',...
        'Position',[74 59.6153846153846 23 4.46153846153847],...
        'Tag','BalloonTempaPanel',...
        'Clipping','off'...
         );

        hs.BalloonTempEntry = uicontrol(...
        'Parent',hs.BalloonTempPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','edit',...
        'Position',[5.2 1 10.4 1.69230769230769],...
        'BackgroundColor',[1 1 1],...
        'Children',[],...
        'Tag','BalloonTemp');

        hs.BalloonTempLabel = uicontrol(...
        'Parent',hs.BalloonTempPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','°F',...
        'Style','text',...
        'Position',[15.8 1.30769230769231 2.2 1.15384615384615],...
        'Children',[],...
        'Tag','text25'...
         );

    end

    function GenPlots_Callback(~,~,hs)
        
        %Creating the Diameter Range
        RangeStart = getNumericVal(hs.DiameterPlotStartEntry);
        RangeStep = getNumericVal(hs.DiameterPlotStepEntry);
        RangeEnd = getNumericVal(hs.DiameterPlotEndEntry);

        Diameter = RangeStart:RangeStep:RangeEnd;

        % calculate values to plot
        [AWOSBurst,LocalBurst] = RunCalcs_Callback(1,1, hs);

        axes(hs.FeetAltDiameter)
        cla;
        hold on
        grid on 
        title 'Burst Diameter vs. Burst Altitude'
        xlabel 'meters'
        ylabel 'feet'
        plot(Diameter,AWOSBurst(:,1),'r')
        plot(Diameter,LocalBurst(:,1),'b')
        plot(Diameter,AWOSBurst(:,2),'g')
        plot(Diameter,LocalBurst(:,2),'k')
        legend('AWOS Standard','Local Standard','AWOS Method','Local Method','Location','Southeast')
        hold off

        axes(hs.MeterAltDiameter)
        cla;
        hold on
        grid on 
        title 'Burst Diameter vs. Burst Altitude in meters'
        xlabel 'meters'
        ylabel 'meters'
        plot(Diameter,AWOSBurst(:,3),'r')
        plot(Diameter,LocalBurst(:,3),'b')
        plot(Diameter,AWOSBurst(:,4),'g')
        plot(Diameter,LocalBurst(:,4),'k')
        legend('AWOS Standard','Local Standard','AWOS Method','Local Method','Location','Southeast')
        hold off
    end

    function rtn = getNumericVal(handle)
    % gets the string property of the handle argument and converts the
    % value to a numeric value
        rtn = get(handle,'String');
        rtn = str2double(rtn);
    end

    function [AWOSBurst,LocalBurst] = RunCalcs_Callback(~, ~, hs)

        %Creating the Diameter Range
        RangeStart = getNumericVal(hs.DiameterPlotStartEntry);
        RangeStep = getNumericVal(hs.DiameterPlotStepEntry);
        RangeEnd = getNumericVal(hs.DiameterPlotEndEntry);

        Diameter = RangeStart:RangeStep:RangeEnd;

        PayloadMass = getNumericVal(hs.PayloadMassEntry);
        DuctTapeFactor = getNumericVal(hs.DuctTapeEntry);
        %Creating the Mass with the safety factor
        TotalMass = PayloadMass * DuctTapeFactor;

        %Creating the Data Vector for AWOSMethod
        LaunchAlt = getNumericVal(hs.LaunchAltEntry);
        AWOSTemp = getNumericVal(hs.AWOSTempEntry);
        AWOSDewPoint = getNumericVal(hs.AWOSDewPtEntry);
        AWOSPress = getNumericVal(hs.AWOSPresEntry);
        BalloonTemp = getNumericVal(hs.BalloonTempEntry);
        AWOSData = [LaunchAlt;AWOSTemp;AWOSDewPoint;AWOSPress;BalloonTemp;TotalMass];
        
        %Running AWOSMethod
        HeliumMass = getNumericVal(hs.HeliumMassEntry);
        [AWOSLift, AWOSBurst, AWOSSpeed, AWOSDelta] = AWOSMethod(AWOSData,Diameter,HeliumMass);

        %Creating the Data Vecotr for LocalMethod
        LaunchAlt = getNumericVal(hs.LaunchAltEntry);
        LocalTemp = getNumericVal(hs.LocalDataTempEntry);
        LocalDewPoint = getNumericVal(hs.LocalDataDewPtEntry);
        LocalPress  = getNumericVal(hs.LocalDataPresEntry);
        LocalData = [LaunchAlt;LocalTemp;LocalDewPoint;LocalPress;BalloonTemp;TotalMass];
        
        %Running LocalMethod
        [LocalLift, LocalBurst, LocalSpeed, LocalDelta] = LocalMethod(LocalData,Diameter,HeliumMass);

        PayloadMass = getNumericVal(hs.PayloadMassEntry);
        Weight = [PayloadMass;TotalMass]*2.2046226218;%Converting to pounds for the weight to display

        %Putting the selected data into the table for display
        set(hs.LiftTable,'data',[AWOSLift, LocalLift])
        set(hs.DeltaLiftTable,'data',[AWOSDelta, LocalDelta])
        set(hs.AscentRateTable,'data',[AWOSSpeed, LocalSpeed])
        set(hs.WeightTable,'data',Weight)

    end

    function hs = setupCallbacks(hs)
    % adds callbacks to ui elements   
    % Note: callbacks must be setup after handle structure is fully
    % initalized
    
        set(hs.TankCalcBtn,'Callback',{@HeliumTankCalc_Callback,hs});
        set(hs.CalcButton,'Callback',{@RunCalcs_Callback,hs});
        set(hs.PlotButton,'Callback',{@GenPlots_Callback,hs});
        set(hs.BalloonMenuCalcBtn,'Callback',{@GenPlots_Callback,hs});
        set(hs.BalloonMenuPlotBtn,'Callback',{@GenPlots_Callback,hs});
        set(hs.BalloonMenuPlotBtn,'Callback',{@closefcn,hs});
        
    end

    function closefcn(~,~,hs)
    % callback for closing the window
    
        close(hs.fig);
    end

    function HeliumTankCalc_Callback(~,~,hs)
    % performs helium tank calculations

        Tank1 = get(hs.Tank1Table,'data');
        Tank2 = get(hs.Tank1Table,'data');
        TankMass1 = HeliumMassCalc(Tank1(1,1),Tank1(1,2),Tank1(2,1),Tank1(2,2));
        TankMass2 = HeliumMassCalc(Tank2(1,1),Tank2(1,2),Tank2(2,1),Tank2(2,2));
        HeliumTankMass = TankMass1 + TankMass2;
        set(hs.TankMassValueLabel, 'String', HeliumTankMass )
    end

    function setdefaultvals(hs)
    % sets the default values of each of the input fields
        
       %Intial data
        set(hs.DuctTapeEntry, 'String', 1.1)
        set(hs.PayloadMassEntry, 'String', 8.500)
        set(hs.HeliumMassEntry, 'String', 2.47)
        set(hs.LocalDataTempEntry, 'String', 69.8)
        set(hs.LocalDataDewPtEntry, 'String', 59)
        set(hs.LocalDataPresEntry, 'String', 1013.25)
        set(hs.AWOSTempEntry, 'String', 21)
        set(hs.AWOSDewPtEntry, 'String', 15)
        set(hs.AWOSPresEntry, 'String', 29.92)
        set(hs.DiameterPlotStartEntry, 'String', 10.5)
        set(hs.DiameterPlotStepEntry, 'String', 0.1)
        set(hs.DiameterPlotEndEntry, 'String', 14.5)
        set(hs.LaunchAltEntry, 'String', 180)
        set(hs.BalloonTempEntry, 'String', 75)

    end

%     function rtnflg = numericEntryValidate(hObject,~,~)
%         
%         val = str2double(get(hObject, 'String'));
%         rtnflg = true;
%         if isnan(val)
%             rtnflg = false;
%         end 
%         % FIXME: add more
%     end
% 
%     function ducttapevalidation()
%         DuctTapeFactor = str2double(get(hObject, 'String'));
%         
%         if numericEntryValidate(DuctTapeFactor)
%             set(hObject, 'String', 1.1);
%             errordlg('Input must be a number','Error');
%         end 
%     end
    
end