%Base Program provided by Steve Lente
%Edited By Michael Walker
function BalloonGUI3()
%Generates a GUI for use in Balloon Performance Analysis
%
%Tank Mass Calculator uses HeliumMassCalc for mass of helium
%The calculate button runs indepedently to calculate the mass
%
%AWOS Data is from an airport's Automated Weather Observing Station, 
%
%Local Data is measurements taken on-site with on-site equipment. The 
%pressure reading must be absolute/station pressure, not adjusted to be sea
%level pressure. 
%
%Payload Weight is given in pounds
%
%The Calculate button runs all the calculations and updates the tables
%The Plot button runs the calculations and plots the burst data
%
%Dependencies:
%HeliumMassCalc, AWOSMethod, LocalMethod
%   and by extention:
% MoistDensity, StandAtmo1976, CustomStandAtmo1976

    % Add the UI components
    hs = addcomponents();
    hs = setupCallbacks(hs);
    setdefaultvals(hs);
    
    % Make figure visible after adding components
    hs.fig.Visible = 'on';

    function hs = addcomponents()

        % create figure
        hs.fig = figure(...
        'Units','characters',...
        'Position',[103.8 -20.4615384615385 185 69.7692307692308],...
        'Visible','on',...
        'Color',get(0,'defaultfigureColor'),...
        'IntegerHandle','off',...
        'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
        'Name','BalloonGUI',...
        'NumberTitle','off',...
        'Tag','figure1',...
        'UserData',[],...
        'resize', 'off', ...
        'PaperPosition',get(0,'defaultfigurePaperPosition'),...
        'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
        'ScreenPixelsPerInchMode','manual',...
        'HandleVisibility','callback','MenuBar','none','Toolbar','figure');
    
        % modify toolbar buttons to remove ones we dont want
        buttons_to_remove = {'New Figure',...
            'Print Figure','Edit Plot','Rotate 3D','Insert Legend','Insert Colorbar'};
        for i = 1:length(buttons_to_remove)
            btn_handle = findall(hs.fig,'ToolTipString',buttons_to_remove{i});
            set(btn_handle,'Visible','Off')
        end
        clear btn_handle buttons_to_remove
        
        %Make Save and Load Buttons Do What they do
        hs.save = findall(hs.fig,'ToolTipString','Save Figure');
        hs.load = findall(hs.fig,'ToolTipString','Open File');
        
        
        
        % add custom menu options
        hs.BalloonMenu = uimenu(...
        'Parent',hs.fig,...
        'Callback',@(hObject,eventdata)BalloonGUI_export('Title_1_Callback',hObject,eventdata,guidata(hObject)),...
        'Label','Balloon Performance Calculations',...
        'Tag','Title_1'...
         );

        hs.BalloonMenuCalcBtn = uimenu(...
            'Parent',hs.BalloonMenu,...
            'Label','Calculate');
        hs.BalloonMenuPlotBtn = uimenu(...
            'Parent',hs.BalloonMenu,...
            'Label','Plot');
        hs.BalloonMenuPlotBtn = uimenu(...
            'Parent',hs.BalloonMenu,...
            'Label','Close');
        
        % Initalize Axes
        hs.FeetAltDiameter = axes(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultaxesFontUnits'),...
        'Units','characters',...
        'CameraPosition',[0.5 0.5 9.16025403784439],...
        'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
        'CameraTarget',[0.5 0.5 0.5],...
        'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
        'CameraViewAngle',6.60861036031192,...
        'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
        'PlotBoxAspectRatio',[1 0.869458128078818 0.869458128078818],...
        'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
        'XTick',[0 0.2 0.4 0.6 0.8 1],...
        'XTickMode',get(0,'defaultaxesXTickMode'),...
        'XTickLabel',{  '0'; '0.2'; '0.4'; '0.6'; '0.8'; '1' },...
        'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
        'YTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
        'YTickMode',get(0,'defaultaxesYTickMode'),...
        'YTickLabel',{  '0'; '0.1'; '0.2'; '0.3'; '0.4'; '0.5'; '0.6'; '0.7'; '0.8'; '0.9'; '1' },...
        'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
        'Color',get(0,'defaultaxesColor'),...
        'CameraMode',get(0,'defaultaxesCameraMode'),...
        'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
        'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
        'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
        'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
        'XGridHandleMode',get(0,'defaultaxesXGridHandleMode'),...
        'YGridHandleMode',get(0,'defaultaxesYGridHandleMode'),...
        'XRulerMode',get(0,'defaultaxesXRulerMode'),...
        'XBaselineMode',get(0,'defaultaxesXBaselineMode'),...
        'YRulerMode',get(0,'defaultaxesYRulerMode'),...
        'YBaselineMode',get(0,'defaultaxesYBaselineMode'),...
        'ZRulerMode',get(0,'defaultaxesZRulerMode'),...
        'ZBaselineMode',get(0,'defaultaxesZBaselineMode'),...
        'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
        'XGrid','on',...
        'YGrid','on',...
        'Tag','FeetAltDiameter',...
        'Position',[9.8 11.7692307692308 81.2 27.1538461538462],...
        'ActivePositionProperty','position',...
        'ActivePositionPropertyMode',get(0,'defaultaxesActivePositionPropertyMode'),...
        'LooseInset',[20.124 7.55615384615385 14.706 5.15192307692308],...
        'SortMethod','childorder',...
        'SortMethodMode',get(0,'defaultaxesSortMethodMode'),...
        'NextPlot','add'...
         );
% 'CreateFcn', {@local_CreateFcn, blanks(0), appdata}

        h3 = get(hs.FeetAltDiameter,'title');

        set(h3,...
        'Parent',hs.FeetAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0.500000594284734 1.0070821529745 0.500000000000007],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','bottom',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','middle',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','Axes Title',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');
%          ,...

        h4 = get(hs.FeetAltDiameter,'xlabel');

        set(h4,...
        'Parent',hs.FeetAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0.500000476837158 -0.0670443800567344 7.105427357601e-15],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','top',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','back',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');
%          ,...

        h5 = get(hs.FeetAltDiameter,'ylabel');

        set(h5,...
        'Parent',hs.FeetAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[-0.0697865339090868 0.500000476837158 7.105427357601e-15],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',90,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','bottom',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','back',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');

        h6 = get(hs.FeetAltDiameter,'zlabel');

        set(h6,...
        'Parent',hs.FeetAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0 0 0],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','right',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','middle',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','middle',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','off',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');


        hs.MeterAltDiameter = axes(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultaxesFontUnits'),...
        'Units','characters',...
        'CameraPosition',[0.5 0.5 9.16025403784439],...
        'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
        'CameraTarget',[0.5 0.5 0.5],...
        'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
        'CameraViewAngle',6.60861036031192,...
        'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
        'PlotBoxAspectRatio',[1 0.869458128078818 0.869458128078818],...
        'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
        'XTick',[0 0.2 0.4 0.6 0.8 1],...
        'XTickMode',get(0,'defaultaxesXTickMode'),...
        'XTickLabel',{  '0'; '0.2'; '0.4'; '0.6'; '0.8'; '1' },...
        'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
        'YTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
        'YTickMode',get(0,'defaultaxesYTickMode'),...
        'YTickLabel',{  '0'; '0.1'; '0.2'; '0.3'; '0.4'; '0.5'; '0.6'; '0.7'; '0.8'; '0.9'; '1' },...
        'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
        'Color',get(0,'defaultaxesColor'),...
        'CameraMode',get(0,'defaultaxesCameraMode'),...
        'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
        'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
        'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
        'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
        'XRulerMode',get(0,'defaultaxesXRulerMode'),...
        'XBaselineMode',get(0,'defaultaxesXBaselineMode'),...
        'YRulerMode',get(0,'defaultaxesYRulerMode'),...
        'YBaselineMode',get(0,'defaultaxesYBaselineMode'),...
        'ZRulerMode',get(0,'defaultaxesZRulerMode'),...
        'ZBaselineMode',get(0,'defaultaxesZBaselineMode'),...
        'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
        'XGrid','on',...
        'YGrid','on',...
        'Tag','MeterAltDiameter',...
        'Position',[99.8 11.7692307692308 81.2 27.1538461538462],...
        'ActivePositionProperty','position',...
        'ActivePositionPropertyMode',get(0,'defaultaxesActivePositionPropertyMode'),...
        'LooseInset',[20.124 7.55615384615385 14.706 5.15192307692308],...
        'SortMethod','childorder',...
        'SortMethodMode',get(0,'defaultaxesSortMethodMode')...
         );

        h8 = get(hs.MeterAltDiameter,'title');

        set(h8,...
        'Parent',hs.MeterAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0.500001651312917 1.0070821529745 0.500000000000007],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','bottom',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','middle',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','Axes Title',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');
%          ,...

        h9 = get(hs.MeterAltDiameter,'xlabel');

        set(h9,...
        'Parent',hs.MeterAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0.500000476837158 -0.0670443800567344 7.105427357601e-15],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','top',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','back',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');

        hs.fig0 = get(hs.MeterAltDiameter,'ylabel');

        set(hs.fig0,...
        'Parent',hs.MeterAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[-0.0697865339090866 0.500000476837158 7.105427357601e-15],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',90,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','center',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','bottom',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','back',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','on',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');
%          ,...

        hs.fig1 = get(hs.MeterAltDiameter,'zlabel');

        set(hs.fig1,...
        'Parent',hs.MeterAltDiameter,...
        'Units','data',...
        'FontUnits','points',...
        'DecorationContainer',[],...
        'DecorationContainerMode','auto',...
        'Color',[0 0 0],...
        'ColorMode','auto',...
        'Position',[0 0 0],...
        'PositionMode','auto',...
        'String',blanks(0),...
        'Interpreter','tex',...
        'Rotation',0,...
        'RotationMode','auto',...
        'FontName','Helvetica',...
        'FontSize',10,...
        'FontAngle','normal',...
        'FontWeight','normal',...
        'HorizontalAlignment','right',...
        'HorizontalAlignmentMode','auto',...
        'VerticalAlignment','middle',...
        'VerticalAlignmentMode','auto',...
        'EdgeColor','none',...
        'LineStyle','-',...
        'LineWidth',0.5,...
        'BackgroundColor','none',...
        'Margin',1,...
        'Clipping','off',...
        'Layer','middle',...
        'LayerMode','auto',...
        'FontSmoothing','on',...
        'FontSmoothingMode','auto',...
        'DisplayName',blanks(0),...
        'IncludeRenderer','on',...
        'IsContainer','off',...
        'IsContainerMode','auto',...
        'HelpTopicKey',blanks(0),...
        'ButtonDownFcn',blanks(0),...
        'BusyAction','queue',...
        'Interruptible','on',...
        'DeleteFcn',blanks(0),...
        'Tag',blanks(0),...
        'HitTest','on',...
        'PickableParts','visible',...
        'PickablePartsMode','auto',...
        'XLimInclude','on',...
        'YLimInclude','on',...
        'ZLimInclude','on',...
        'CLimInclude','on',...
        'ALimInclude','on',...
        'Description','AxisRulerBase Label',...
        'DescriptionMode','auto',...
        'Visible','off',...
        'Serializable','on',...
        'HandleVisibility','off',...
        'TransformForPrintFcnImplicitInvoke','on',...
        'TransformForPrintFcnImplicitInvokeMode','auto');


        hs.ButtonsPanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','characters',...
        'Title',blanks(0),...
        'Position',[41.4 48.2 41.2 3.84615384615385],...
        'Tag','ButtonsPanel',...
        'Clipping','off'...
         );

        hs.CalcButton = uicontrol(...
        'Parent',hs.ButtonsPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Calculate',...
        'Position',[2.4 0.846153846153846 15.6 1.92307692307692],...
        'Children',[],...
        'Tag','RunCalcs'...
         );

        hs.PlotButton = uicontrol(...
        'Parent',hs.ButtonsPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Plot',...
        'Position',[22 0.846153846153846 15.6 1.92307692307692],...
        'Children',[],...
        'Tag','GenPlots'...
         );

        appdata = [];
        appdata.lastValidTag = 'Diameter';
        appdata.PropertyMetaData = {  {  'DataPropertyDimension' 'DataPropertyConditionedDimension' 'DataPropertySource' 'BackgroundColorPropertyDimension' 'ColumnNameTyped' 'RowNameTyped' } {  [] 'DataExisting' [] {  'Diameter'  } {  'Start' 'Step' 'End' } } };

     
        hs.DiameterPlotTable = uitable(...
        'Parent',hs.fig,...
        'Units','character',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{'Diameter Plot Range'},...
        'ColumnWidth',{  'auto' },...
        'RowName',{'Start'; 'Step'; 'End'},...
        'Position',[58.4 62.0 38.0 6.1],...
        'ColumnEditable',true,...
        'ColumnFormat',{  [] },...
        'Data',[10.5;0.1;13.5],...
        'Children',[],...
        'Tag','Diameter',...
        'UserData',[]...
         );
     
        appdata = [];
        appdata.lastValidTag = 'WeatherData';
        appdata.PropertyMetaData = {  {  'DataPropertyDimension' 'DataPropertyConditionedDimension' 'DataPropertySource' 'BackgroundColorPropertyDimension' 'ColumnNameTyped' 'RowNameTyped' } {  [] 'DataExisting' [] {  'WeatherData' } {  'Temperature' 'DewPoint' 'Pressure' } } };
     
        hs.WeatherDataTable = uitable(...
        'Parent',hs.fig,...
        'Units','character',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'AWOS Data' 'Local Data' },...
        'ColumnWidth',{  'auto'  },...
        'RowName',{'Temperature'; 'DewPoint'; 'Presssure'},...
        'Position',[2.4 62.0 55.2 6.1],...
        'ColumnEditable',true,...
        'ColumnFormat',{ [] [] },...
        'Data',[21, 21; 15, 15; 29.92, 1013.25],...
        'Children',[],...
        'Tag','WeatherData',...
        'UserData',[]...
         );
     
     hs.LaunchDataTable = uitable(...
        'Parent',hs.fig,...
        'Units','character',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'Data' },...
        'ColumnWidth',{  'auto'  },...
        'RowName',{'Launch Altitude'; 'Balloon Temperature'; 'Helium Mass'; 'Payload Mass'; 'Duct Tape Factor' },...
        'Position',[2.4 52.5 57.8 8.8],...
        'ColumnEditable',true,...
        'ColumnFormat',{ [] },...
        'Data',[0; 75; 2.47; 8.5; 1.1],...
        'Children',[],...
        'Tag','AWOSData',...
        'UserData',[]...
         );
     
        hs.LiftTable = uitable(...
        'Parent',hs.fig,...
        'Units','characters',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'AWOS Data'; 'Local Data' },...
        'ColumnWidth',{  'auto' 'auto' },...
        'Position',[16.6 41.5384615384615 36.8 4.76923076923077],...
        'ColumnEditable',[false false],...
        'ColumnFormat',{  [] [] },...
        'Data',[25.9432791808011 25.81763418819;25.9434446204095 26.0946963894714],...
        'Children',[],...
        'Tag','Lift',...
        'UserData',[]...
         );
     
        hs.LiftTabelLabel = uicontrol(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Lift in pounds',...
        'Style','text',...
        'Position',[22.2 46.3076923076923 27.6 1.15384615384615],...
        'Children',[],...
        'Tag','text28'...
         );

        hs.DeltaLiftTable = uitable(...
        'Parent',hs.fig,...
        'Units','characters',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'AWOS Data'; 'Local Data' },...
        'ColumnWidth',{  'auto' 'auto' },...
        'Position',[97 41.6923076923077 37 4.61538461538461],...
        'ColumnEditable',[false false],...
        'ColumnFormat',{  [] [] },...
        'Data',[2.11924534996703 1.99360035735588;2.11941078957542 2.27066255863736],...
        'Children',[],...
        'Tag','Delta',...
        'UserData',[]...
         );
     
        hs.DeltaLiftTableLabel = uicontrol(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Delta Lift [lbs]',...
        'Style','text',...
        'Position',[102.2 46.3076923076923 27.6 1.15384615384615],...
        'Children',[],...
        'Tag','text29'...
         );

        hs.AscentRateTable = uitable(...
        'Parent',hs.fig,...
        'Units','characters',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'AWOS Data'; 'Local Data' },...
        'ColumnWidth',{  'auto' 'auto' },...
        'Position',[136 41.6923076923077 37 4.61538461538461],...
        'ColumnEditable',[false false],...
        'ColumnFormat',{  [] [] },...
        'Data',[5.47986568267108 5.35341122239389;5.47925296461384 5.62483848444981],...
        'Children',[],...
        'Tag','Speed',...
        'UserData',[]...
         );
     
        hs.AscentRateTableLabel = uicontrol(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Ascent Rate [m/s]',...
        'Style','text',...
        'Position',[139.8 46.3076923076923 27.6 1.15384615384615],...
        'Children',[],...
        'Tag','text30'...
         );
     
        hs.WeightTable = uitable(...
        'Parent',hs.fig,...
        'Units','characters',...
        'ColumnName',{  'Payload Weight' },...
        'ColumnWidth',{  'auto' },...
        'RowName',{  'True'; 'w/factor' },...
        'Position',[57.4 41.3076923076923 36.2 5],...
        'ColumnEditable',false,...
        'ColumnFormat',{  [] },...
        'Data',[21.6582126365632;23.8240339002195],...
        'Children',[],...
        'Tag','Weight',...
        'UserData',[]...
         );

        hs.TankMassCalcPanel = uipanel(...
        'Parent',hs.fig,...
        'FontUnits',get(0,'defaultuipanelFontUnits'),...
        'Units','characters',...
        'TitlePosition','centertop',...
        'Title','Tank Mass Calculator',...
        'Position',[101.8 49 68.6 19],...
        'Tag','TankMassCalcPanel',...
        'Clipping','off'...
         );

        appdata = [];
        appdata.lastValidTag = 'Tank1';
        appdata.PropertyMetaData = {  {  'DataPropertyDimension' 'DataPropertyConditionedDimension' 'DataPropertySource' 'BackgroundColorPropertyDimension' 'ColumnNameTyped' 'RowNameTyped' } {  [] [] 'DataExisting' [] {  'Tank 1 Start' 'Tank 1 End' } {  'Pressure' 'Temperature' } } };

        hs.Tank1Table = uitable(...
        'Parent',hs.TankMassCalcPanel,...
        'Units','characters',...
        'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
        'ColumnName',{  'Tank 1 Start'; 'Tank 1 End' },...
        'ColumnWidth',{  'auto' 'auto' },...
        'RowName',{  'Pressure'; 'Temperature' },...
        'Position',[3.8 12 55.2 4.7],...
        'ColumnEditable',[true true],...
        'ColumnFormat',{  [] [] },...
        'Data',[2500 100;70 60],...
        'Children',[],...
        'Tag','Tank1',...
        'UserData',[]...
         );

        appdata = [];
        appdata.lastValidTag = 'Tank2';
        appdata.PropertyMetaData = {  {  'DataPropertyDimension' 'DataPropertyConditionedDimension' 'DataPropertySource' 'BackgroundColorPropertyDimension' 'ColumnNameTyped' 'RowNameTyped' } {  [] [] 'DataExisting' [] {  'Tank 2 Start' 'Tank 2 End' } {  'Pressure' 'Temperature' } } };

        hs.Tank2Table = uitable(...
        'Parent',hs.TankMassCalcPanel,...
        'Units','characters',...
        'ColumnName',{  'Tank 2 Start'; 'Tank 2 End' },...
        'ColumnWidth',{  'auto' 'auto' },...
        'RowName',{  'Pressure'; 'Temperature' },...
        'Position',[3.8 6.5 55.2 4.7],...
        'ColumnEditable',[true true],...
        'ColumnFormat',{  [] [] },...
        'Data',[2500 100;70 60],...
        'Children',[],...
        'Tag','Tank2',...
        'UserData',[]...
         );

        hs.TankCalcBtn = uicontrol(...
        'Parent',hs.TankMassCalcPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','Calculate',...
        'Position',[3.6 2.30769230769231 22.4 2.23076923076923],...
        'Children',[],...
        'Tag','HeliumTankCalc'...
         );
     
        hs.TankMassValueLabel = uicontrol(...
        'Parent',hs.TankMassCalcPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','0',...
        'Style','text',...
        'Position',[31.8 3 12.2 1.15384615384615],...
        'Children',[],...
        'Tag','HeliumTankMass'...
         );

        hs.TankMassLabel = uicontrol(...
        'Parent',hs.TankMassCalcPanel,...
        'FontUnits',get(0,'defaultuicontrolFontUnits'),...
        'Units','characters',...
        'String','kg',...
        'Style','text',...
        'Position',[44 3 2.8 1.15384615384615],...
        'Children',[],...
        'Tag','text27'...
         );

       
    end

    function GenPlots_Callback(~,~,hs)
        
        %Creating the Diameter Range
        Range = get(hs.DiameterPlotTable,'Data');
        Diameter = Range(1):Range(2):Range(3);


        % calculate values to plot
        [AWOSBurst,LocalBurst] = RunCalcs_Callback(1,1, hs);
        
        axes(hs.FeetAltDiameter)
        cla;
        hold on
        grid on 
        title 'Burst Diameter vs. Burst Altitude'
        xlabel 'meters'
        ylabel 'feet'
        plot(Diameter,AWOSBurst(:,1),'r')
        plot(Diameter,LocalBurst(:,1),'b')
        plot(Diameter,AWOSBurst(:,2),'g')
        plot(Diameter,LocalBurst(:,2),'k')
        legend('AWOS Standard','Local Standard','AWOS Method','Local Method','Location','Southeast')
        hold off

        axes(hs.MeterAltDiameter)
        cla;
        hold on
        grid on 
        title 'Burst Diameter vs. Burst Altitude in meters'
        xlabel 'meters'
        ylabel 'meters'
        plot(Diameter,AWOSBurst(:,3),'r')
        plot(Diameter,LocalBurst(:,3),'b')
        plot(Diameter,AWOSBurst(:,4),'g')
        plot(Diameter,LocalBurst(:,4),'k')
        legend('AWOS Standard','Local Standard','AWOS Method','Local Method','Location','Southeast')
        hold off
    end

    function rtn = getNumericVal(handle)
    % gets the string property of the handle argument and converts the
    % value to a numeric value
        rtn = get(handle,'String');
        rtn = str2double(rtn);
    end

    function [AWOSBurst,LocalBurst] = RunCalcs_Callback(~, ~, hs)

        %Creating the Diameter Range
        Range = get(hs.DiameterPlotTable,'Data'); %Start Step End
        LaunchData = get(hs.LaunchDataTable,'Data'); %Launch Altitude; Balloon Temperature; Helium Mass; Payload Mass; Duct Tape Factor
        
        Diameter = Range(1):Range(2):Range(3);
        
        %Creating the Mass with the safety factor
        TotalMass = LaunchData(4) * LaunchData(5);

        %Creating the Data Vector for AWOSMethod
        Weather = get(hs.WeatherDataTable,'Data');
        AWOSData = [LaunchData(1);Weather(1,1);Weather(2,1);Weather(3,1);LaunchData(2);TotalMass];
        
        %Running AWOSMethod
        [AWOSLift, AWOSBurst, AWOSSpeed, AWOSDelta] = AWOSMethod(AWOSData,Diameter,LaunchData(3));

        %Creating the Data Vecotr for LocalMetho
        LocalData = [LaunchData(1);Weather(1,2);Weather(2,2);Weather(3,2);LaunchData(2);TotalMass];
        
        %Running LocalMethod
        [LocalLift, LocalBurst, LocalSpeed, LocalDelta] = LocalMethod(LocalData,Diameter,LaunchData(3));

        Weight = [LaunchData(4);TotalMass]*2.2046226218;%Converting to pounds for the weight to display

        %Putting the selected data into the table for display
        set(hs.LiftTable,'data',[AWOSLift, LocalLift])
        set(hs.DeltaLiftTable,'data',[AWOSDelta, LocalDelta])
        set(hs.AscentRateTable,'data',[AWOSSpeed, LocalSpeed])
        set(hs.WeightTable,'data',Weight)

    end

    function hs = setupCallbacks(hs)
    % adds callbacks to ui elements   
    % Note: callbacks must be setup after handle structure is fully
    % initalized
    
        set(hs.TankCalcBtn,'Callback',{@HeliumTankCalc_Callback,hs});
        set(hs.CalcButton,'Callback',{@RunCalcs_Callback,hs});
        set(hs.PlotButton,'Callback',{@GenPlots_Callback,hs});
        set(hs.BalloonMenuCalcBtn,'Callback',{@GenPlots_Callback,hs});
        set(hs.BalloonMenuPlotBtn,'Callback',{@GenPlots_Callback,hs});
        set(hs.BalloonMenuPlotBtn,'Callback',{@closefcn,hs});
        set(hs.save,'ClickedCallback',{@savebutton,hs});
        set(hs.load,'ClickedCallback',{@loadbutton,hs});
    end

    function closefcn(~,~,hs)
    % callback for closing the window
    
        close(hs.fig);
    end

    function HeliumTankCalc_Callback(~,~,hs)
    % performs helium tank calculations

        Tank1 = get(hs.Tank1Table,'data');
        Tank2 = get(hs.Tank2Table,'data');
        TankMass1 = HeliumMassCalc(Tank1(1,1),Tank1(1,2),Tank1(2,1),Tank1(2,2));
        TankMass2 = HeliumMassCalc(Tank2(1,1),Tank2(1,2),Tank2(2,1),Tank2(2,2));
        HeliumTankMass = TankMass1 + TankMass2;
        set(hs.TankMassValueLabel, 'String', HeliumTankMass )
    end

    function setdefaultvals(hs)
    % sets the default values of each of the input fields
        
       %Intial data
        set(hs.WeatherDataTable, 'Data', [21, 21; 15, 15; 29.92, 1013.25])
        set(hs.DiameterPlotTable, 'Data', [10.5; 0.1; 13.5] )
        set(hs.LaunchDataTable, 'Data', [0; 75; 2.47; 8.5; 1.1])
        

    end

    function savebutton(~,~,hs)
        %function for saveing data
        FileName = uiputfile('default.txt','Save File Data');
        WeatherData = get(hs.WeatherDataTable, 'Data');
        PlotData = get(hs.DiameterPlotTable, 'Data');
        LaunchData = get(hs.LaunchDataTable, 'Data');
        Tank1 = get(hs.Tank1Table,'Data');
        Tank2 = get(hs.Tank2Table,'Data');
        
        %Building the data to save
        FileData = [WeatherData(:,1); WeatherData(:,2); PlotData; LaunchData; Tank1(:,1); Tank1(:,2); Tank2(:,1); Tank2(:,2)];
       
        File = fopen(FileName,'wt');
        for n = 1:length(FileData)
           fprintf(File,'%f\n',FileData(n));
        end
        fclose(File);
    end

    function loadbutton(~,~,hs)
        %function for loading data
        FileName = uigetfile({'*.txt';'*.m';'*.*'},'File Selector');
        File = fopen(FileName,'r');
        FileData = fscanf(File,'%f\n',[1 Inf]);
        fclose(File);
        
        if (length(FileData) == 22)
        
        %Building data sets
        WeatherData = [FileData(1:3)', FileData(4:6)' ];
        PlotData = FileData(7:9)';
        LaunchData = FileData(10:14)';
        Tank1 = [FileData(15:16)', FileData(17:18)'];
        Tank2 = [FileData(19:20)', FileData(21:22)'];
        
        %Loading into GUI
        set(hs.WeatherDataTable,'Data', WeatherData)
        set(hs.DiameterPlotTable,'Data', PlotData)
        set(hs.LaunchDataTable,'Data', LaunchData)
        set(hs.Tank1Table,'Data',Tank1)
        set(hs.Tank2Table,'Data',Tank2)
        
        else
        disp('Invalid File Selected')
        end

        
    end




%     function rtnflg = numericEntryValidate(hObject,~,~)
%         
%         val = str2double(get(hObject, 'String'));
%         rtnflg = true;
%         if isnan(val)
%             rtnflg = false;
%         end 
%         % FIXME: add more
%     end
% 
%     function ducttapevalidation()
%         DuctTapeFactor = str2double(get(hObject, 'String'));
%         
%         if numericEntryValidate(DuctTapeFactor)
%             set(hObject, 'String', 1.1);
%             errordlg('Input must be a number','Error');
%         end 
%     end
    
end